name: Chess Chat CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: switch to main branch
      run: git checkout main

    - name: set up java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: check Java code format
      uses: super-linter/super-linter@v6.3.0

    - name: build with gradle
      run: |
        chmod +x ./gradlew
        ./gradlew build

    - name: run project tests
      run: ./gradlew test
